# Generated by Django 3.2.24 on 2024-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20240305_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
