# Generated by Django 3.2.24 on 2024-03-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
